name: scan-code
on: 
  pull_request:
    branches:
      - main
jobs:
  apex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup PMD
      uses: legetz/setup-pmd@7.1.0
    - name: APEX full scan
      run: pmd check --dir ./force-app/main/default/classes/*.cls --rulesets ./pmd-rules.xml -f text
